### PR TITLE
Added support for rewarded video, Android Studio and Gradle

### PR DESCRIPTION
**Pull request by luc4smoreira**
Support for:
- Android Studio with Gradle 
- No need to use a jar file manually extracted from Google Play Servies
- Batch file to build SWC and JAR
- Rewarded videos
- Play-Services-Ads:16.0.0

### CODE REVIEW

**Comment by pozirk** [comment]
One questions though, how others can set their APPLICATION_ID?
We need some explanation in readme file.

**Comment by luc4smoreira** [comment]
This is not [ the current version of Admob (19.3.0) ](https://developers.google.com/admob/android/rel-notes)

I couldn't build the Air Native Extension with the latest version. After the version 16.0.0 the app crashes with this erro:

```

java.lang.NoClassDefFoundError: com.google.android.gms.common.R$string
        at com.google.android.gms.common.api.internal.GoogleServices.<init>(Unknown Source:3)
        at com.google.android.gms.common.api.internal.GoogleServices.initialize(Unknown Source:44)
``` 

I think it's not hard to improve the ANE to fix the error and update to the last version. Maybe it can be fixed following these instructions: [Including resources in your native extension package ](https://help.adobe.com/en_US/air/extensions/WSf268776665d7970d-2e74ffb4130044f3619-7ff8.html):

But I don't have more time to work with this now; So this is the point I was able to move forward. 

Version 16.0.0 doesn't require a APPLICATION_ID yet. But when it is necessary (later version) just add the following lines to your AIR Aplication-app.xml file inside manifestAdditions section, [as described here](https://developers.google.com/admob/android/quick-start#update_your_androidmanifestxml)


```
<!-- Sample AdMob App ID: ca-app-pub-3940256099942544~3347511713 -->
        <meta-data
            android:name="com.google.android.gms.ads.APPLICATION_ID"
            android:value="ca-app-pub-xxxxxxxxxxxxxxxx~yyyyyyyyyy"/>

```

**Comment by pozirk** [comment]
Let me know, when/if you have a game on Google Play with ads, I'll mention it in readme.
Thanks a lot!

**Comment by luc4smoreira** [comment]
I will try to improve more  this ANE later 

Pay me a beer when I go visit Canada

**Pull request merged**
